# Symmetric vs. Asymmetric Semantic Search

A critical distinction for your setup is symmetric vs. asymmetric semantic search:

For *symmetric semantic search* your query and the entries in your corpus are of about the same length and have the same amount of content. An example would be searching for similar questions: Your query could for example be “How to learn Python online?” and you want to find an entry like “How to learn Python on the web?”. For symmetric tasks, you could potentially flip the query and the entries in your corpus.


For *asymmetric semantic search*, you usually have a short query (like a question or some keywords) and you want to find a longer paragraph answering the query. An example would be a query like “What is Python” and you want to find the paragraph “Python is an interpreted, high-level and general-purpose programming language. Python’s design philosophy …”. For asymmetric tasks, flipping the query and the entries in your corpus usually does not make sense.

It sounds like *asymmetric semantic search* is the better aproach to searching through the *resume* text.

In [126]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../data/temp_data")

roll_calls_file = DATA_DIR / "parliament" / "roll_calls_resume.csv"
candidate_test_file = DATA_DIR / "candidate_test" / "Kandidattestdata.xlsx"

df_roll_calls = pd.read_csv(roll_calls_file)
df_FV11 = pd.read_excel(candidate_test_file, sheet_name="FV11")
df_FV15 = pd.read_excel(candidate_test_file, sheet_name="FV15")
df_FV19 = pd.read_excel(candidate_test_file, sheet_name="FV19")
df_FV22 = pd.read_excel(candidate_test_file, sheet_name="FV22")

print(df_roll_calls.shape)
print(df_roll_calls.columns.tolist())
print(df_FV11.shape)
print(df_FV11.columns.tolist())

(2128, 12)
['afstemningid', 'sagstrinid', 'kommentar', 'afstemningstypeid', 'dato', 'sagstrintypeid', 'sagid', 'sagstypeid', 'sag_nummer', 'sag_titel', 'sag_titelkort', 'sag_resume']
(14540, 12)
['id', 'Firstname', 'Lastname', 'Candidates.Party', 'Storkreds', 'gender', 'birthdate', 'Question', 'Answer', 'Answer (Text)', 'IsImportant', 'Comment']

In [127]:
df_FV22.columns.tolist()

['id',
 'Candidates.Firstname',
 'Candidates.Lastname',
 'Candidates.Party',
 'Candidates.Area',
 'gender',
 'birthdate',
 'Question',
 'Answer',
 'Answer (text)',
 'IsImportant',
 'Comment']

In [128]:
# We don't need duplicate questions, so we can drop them and reset the index
df_questions_FV22 = (
    df_FV22[["Question"]]
    .drop_duplicates()
    .dropna()
    .reset_index(drop=True)
)

print(df_questions_FV22.shape)

df_questions_FV22.head(20)

(51, 1)

                                                                                            Question
0                  Afgiften på såkaldte hybridbiler bør være den samme som på benzin- og dieselbiler
1                                           Aldersgrænsen for at købe øl og vin skal hæves til 18 år
2   Asylansøgere bør sendes til et land uden for EU - f.eks. Rwanda - mens deres ansøgning behandles
3                Behandling hos tandlægen bør være gratis for borgerne ligesom andre sundhedsydelser
4                                          Brugen af ukrudtsmidlet Roundup bør forbydes i landbruget
5                                                        Danmark bør indføre CO2-afgift på flyrejser
6                                                        Danmark bør tage imod flere kvoteflygtninge
7       Danmark skal bruge flere penge på at styrke tog- og busdrift frem for at bygge nye motorveje
8                 Danmark skal undersøge muligheden for at udvikle A-kraft som energikilde herhjemme
9                                                           Den såkaldte Arne-pension skal afskaffes
10                                                        Der bør dannes en regering hen over midten
11                                          Der bør åbnes for mere udenlandsk arbejdskraft i Danmark
12                 Der skal afsættes penge til at hjælpe kontanthjælpsmodtagere, når priserne stiger
13                                    Der skal indføres en særlig skat på de allerhøjeste indkomster
14        Der skal indføres kvoter, der sikrer mindst 30 procent kvinder i virksomheders bestyrelser
15                                          Der skal indføres skat på fortjenesten ved salg af bolig
16                                     Der skal udflyttes flere uddannelsespladser fra de store byer
17                                  Der skal være permanent grænsekontrol mellem Danmark og Tyskland
18       Det er en god idé med naturnationalparker, hvor der bliver udsat store dyr, som lever vildt
19                                   Det er en god idé, at dagpengesatsen for nyuddannede er sat ned

In [129]:
df_questions_FV22["election"] = "FV22"

In [130]:
def get_unique_questions(df, election):
    out = (
        df[["Question"]]
        .drop_duplicates()
        .dropna()
        .reset_index(drop=True)
    )
    
    out["election"] = election
    return out


df_questions_FV11 = get_unique_questions(df_FV11, "FV11")
df_questions_FV15 = get_unique_questions(df_FV15, "FV15")
df_questions_FV19 = get_unique_questions(df_FV19, "FV19")
df_questions_FV22 = get_unique_questions(df_FV22, "FV22")

In [131]:
df_questions = pd.concat(
    [
        df_questions_FV11,
        df_questions_FV15,
        df_questions_FV19,
        df_questions_FV22,
    ],
    ignore_index=True,
)

In [132]:
df_cases = (
    df_roll_calls[
        [
            "sagid",
            "sag_nummer",
            "sag_titel",
            "sag_titelkort",
            "sag_resume",
            "dato",
        ]
    ]
    .drop_duplicates(subset="sagid")
    .reset_index(drop=True)
)

In [133]:
df_cases["text"] = (
    df_cases["sag_titel"].fillna("")
    + " "
    + df_cases["sag_resume"].fillna("")
)

In [134]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "intfloat/multilingual-e5-base"
)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4492.12it/s]

In [135]:
# Picking a random question from FV22 to test the embedding model

df_questions.sample(10, random_state=42)
question = df_questions.iloc[73]["Question"]

print(question)

Integrationsydelsen skal hæves

### Embed all parliamentary cases using the asymmetric way

In [136]:
# Full text embeddings 
case_texts = [
    f"passage: {text}"
    for text in df_cases["text"]
]

case_embeddings_texts = model.encode_document(
    case_texts,
    normalize_embeddings=True,
    show_progress_bar=True,
)

Batches:   0%|          | 0/67 [00:00<?, ?it/s]

Batches: 100%|██████████| 67/67 [00:33<00:00,  2.00it/s]

In [142]:
# Only title embeddings
case_titles = [
    f"passage: {title}"
    for title in df_cases["sag_titel"]
]

case_embeddings_titles = model.encode_document(
    case_titles,
    normalize_embeddings=True,
    show_progress_bar=True,
)

Batches: 100%|██████████| 67/67 [00:08<00:00,  8.24it/s]

In [144]:
# Then embed the query question

query_embedding = model.encode_query(
    [f"query: {question}"],
    normalize_embeddings=True,
)

In [145]:
similarities_texts = query_embedding @ case_embeddings_texts.T
similarities_titles = query_embedding @ case_embeddings_titles.T

In [147]:
# Retrieve the top 10 most similar cases of full text embeddings 

import numpy as np

top_k = 10

top_indices = np.argsort(
    similarities_texts[0]
)[::-1][:top_k]

results_text = df_cases.iloc[top_indices].copy()

results_text["similarity"] = similarities_texts[0][top_indices]

results_text[
    [
        "similarity",
        "sag_nummer",
        "sag_titel",
        "sag_resume",
    ]
]

,similarity,sag_nummer,sag_titel,sag_resume
665,0.863359,L 120,"Forslag til lov om ændring af lov om aktiv socialpolitik, integrationsloven, lov om en aktiv beskæftigelsesindsats og ligningsloven. (Nedsættelse af integrationsydelse og omlægning af dansktillæg).","Med lovforslaget nedsættes integrationsydelsen med 3 pct. for at skabe incitament til at tage et arbejde. Samtidig omlægges dansktillægget til en tidsbegrænset danskbonus bestående af seks rater af 1.500 kr. pr. måned. Derudover indføres en danskbonus på 6.000 kr. til personer på integrationsprogrammet, der ikke er omfattet af integrationsydelse."
1326,0.860468,L 202,Forslag til lov om ændring af lov om integrationsgrunduddannelse (igu). (Udvidelse af målgruppen m.v. for integrationsgrunduddannelsen).,"Det foreslås med lovforslaget, at opholdsbetingelsen for integrationsuddannelsesforløb udvides med 5 år, således at flygtninge og familiesammenførte til flygtninge, som har været i Danmark i 0-10 år, fremover får mulighed for at tage et integrationsgrunduddannelsesforløb. Derudover foreslås det, at omfanget af uddannelse i form af amu og sprogkurser udvides med 3 uger, hvorved der samlet set vil være 23 ugers uddannelse i et samlet integrationsgrundsuddannelsesforløb. \n\nLovforslaget udmønter dele af trepartsaftalen af 21. december 2020 mellem regeringen (Socialdemokratiet) og arbejdsmarkedets parter om at udvide og forbedre integrationsuddannelsesforløb.\n\nDet foreslås, at loven træder i kraft den 1. maj 2021, og at de foreslåede regler alene gælder for integrationsgrunduddannelsesforløb, der påbegyndes den 1. maj 2021 eller senere.\n"
765,0.859450,L 231,"Forslag til lov om ændring af udlændingeloven. (Reform af reglerne om ægtefællesammenføring med nyt integrationskrav i stedet for tilknytningskravet, skærpet boligkrav m.v.).","Formålet med lovforslaget er at stramme ægtefællesammenføringsreglerne, bl.a. ved at styrke fokus på, om begge ægtefæller har udsigt til en vellykket integration i Danmark.\n\nMed lovforslaget erstattes det gældende tilknytningskrav med et integrationskrav. Integrationskravet medfører, at ægtefællesammenføring som hovedregel kun kan gives, hvis den herboende ægtefælle har sprogkundskaber, der svarer til Prøve i Dansk 3, og hvis ægtefællerne samlet set opfylder tre ud af fem øvrige betingelser vedrørende sprogkundskaber, erhvervserfaring og uddannelse. \n\nLovforslaget viderefører de hidtidige regler om, at ægtefællesammenføring normalt kun kan gives, hvis den ægtefælle, der kommer hertil, har haft mindst ét lovligt ophold i Danmark. Derudover skærpes de overførte betingelser i reglerne om ægtefællesammenføring, så de svarer til reglerne for tidsubegrænset opholdstilladelse.\n\nLovforslaget indeholder desuden en skærpelse af boligkravet. Boligen må fremover ikke ligge i bestemte boligområder, som optages på boligkravslisten for ægtefællesammenføring. Udlændinge- og integrationsministeren fastsætter de nærmere regler om kriterierne for optagelse af boligområder på listen og offentliggør, hvilke boligområder der er omfattet af boligkravslisten for ægtefællesammenføring. \n\nDen økonomiske sikkerhedsstillelse ved ægtefællesammenføring hæves til 100.000 kr. (i 2018-niveau) mod i dag 50.000 kr. (55.375,27 kr. i 2018-niveau), og reglerne om gradvis nedsættelse af sikkerhedsstillelsen justeres.\n\nDerudover udvides sprogkravet til den ægtefælle, der kommer hertil, så man fremover udover at bestå en danskprøve på A1-niveau inden 6 måneder også skal bestå en danskprøve på A2-niveau eller lignende senest 9 måneder efter tilmelding til folkeregisteret eller fra meddelelse af tilladelse til familiesammenføring.\n\nLovforslaget er en del af udmøntningen af aftalen af 7. februar 2018 mellem regeringen (Venstre, Liberal Alliance og Konservative Folkeparti), Dansk Folkeparti og Socialdemokratiet om stramme, afbalancerede og realistiske regler for ægtefællesammenføring, hvor integrationen er i centrum."
1756,0.859168,L 82,Forslag til lov om ændring af lov om integrationsgrunduddannelse (igu) og lov om Arbejdsgivernes Uddannelsesbidrag. (Videreførelse og udvidelse af igu-ordningen og videreførelse af egu-fgu-bonusordningen).,"Formålet med forslaget er at videreføre og udvide integrationsgrunduddannelsesordningen (igu). Forslaget indebærer, at igu-ordningen og egu-bonussen videreføres i 4 år frem til den 31. december 2027. Forslaget bygger på en aftale mellem regeringen (Socialdemokratiet, Venstre og Moderaterne) og arbejdsmarkedets parter på baggrund af en anbefaling fra Reformkommissionen. \n\nDerudover indebærer forslaget, at persongruppen, som har adgang til ordningen, udvides til at omfatte alle former for familiesammenførte i alderen 18-40 år, som har været i Danmark i op til 20 år. I forlængelse heraf indføres der et årligt loft over antallet af nye igu-forløb på 1.500, hvor der efter behov og nærmere drøftelse i aftalekredsen kan indføres et midlertidigt stop, når der i det enkelte år er påbegyndt 1.200 igu-forløb. Forslaget vil endvidere give udlændinge- og integrationsministeren mulighed for at fastsætte nærmere regler for udstedelse af beviser til fuldførte og delvis gennemførte igu-forløb. \n\nForslaget indebærer også, at egu-fgu-bonusordningen forlænges med 4 år. \n\nDet foreslås, at loven træder i kraft den 1. januar 2024.\n"
143,0.855617,L 2,"Forslag til lov om ændring af lov om aktiv socialpolitik, lov om en aktiv beskæftigelsesindsats, integrationsloven og forskellige andre love. (Indførelse af en integrationsydelse, ændring af reglerne om ret til uddannelses- og kontanthjælp m.v.).","Formålet med lovforslaget er at give nytilkomne udlændinge et større incitament til at arbejde og blive integreret i det danske samfund.\n\nMed lovforslaget indføres der en integrationsydelse i stedet for uddannelseshjælp eller kontanthjælp for nytilkomne flygtninge og familiesammenførte udlændinge og personer, der ikke har boet i Danmark gennem en længere periode. Det er en betingelse for retten til uddannelseshjælp og kontanthjælp, at ansøgeren lovligt har opholdt sig her i riget i sammenlagt mindst 7 år ud af de seneste 8 år. \n\nLoven træder i kraft den 1. september 2015.\n"
978,0.855496,L 19,"Forslag til lov om ændring af lov om social pension, lov om højeste, mellemste, forhøjet almindelig og almindelig førtidspension m.v. og lov om en skattefri seniorpræmie. (Forhøjelse af fradragsbeløb for folkepension og førtidspension og forøgelse af skattefri seniorpræmie).","Lovforslaget udmønter dele af ”Aftale om ret til seniorpension for nedslidte”, og det foreslås\n\n- at bundfradraget for folkepensionisters indtægt ved personligt arbejde forhøjes fra 100.008 kr. til 122.004 kr. om året\n\n- at aftrapningen lempes for folkepensionister og førtidspensionister på gammel ordning (med tilkendelse før 2003), der er gift eller samlevende med en ikke-pensionist, fra 50 procent af indtægten op til 307.700 kr. til 54 procent af hele indtægten uden loft.\n\n- at det maksimale fradrag på 236.728 kr. i pensionistens indtægtsgrundlag for ikke-pensioneret ægtefælle og samlevers indtægter forhøjes med 13.000 kr. til 249.728 kr. (2019-niveau).\n\n- at den skattefrie seniorpræmie øges fra 30.000 kr. til 42.000 kr.\n\n- at der indføres en ny skattefri seniorpræmie på 25.000 kr. for beskæftigelses, det andet år efter AT folkepensionsalderen er nået.\n\nDesuden foreslås det, at lovforslaget får tilbagevirkende kraft fra 1. januar 2019. \n"
240,0.855487,L 111,"Forslag til lov om ændring af lov om aktiv socialpolitik, integrationsloven og forskellige andre love. (Udvidelse af personkredsen for modtagelse af integrationsydelse m.v.).","Med lovforslaget foreslås det, at målgruppen for integrationsydelsen udvides til at omfatte alle personer, som ikke har opholdt sig i Danmark i mindst 7 ud af de seneste 8 år. Formålet med udvidelsen er at styrke målgruppens incitament til at komme i arbejde og blive selvforsørgende og blive integreret i det danske samfund.\n\nFolketinget indførte ved lov nr. 1000 af 30. august 2015 et opholdskrav for ret til uddannelseshjælp og kontanthjælp og en ny, lavere integrationsydelse for personer, der ikke opfylder dette opholdskrav. Loven omfatter ikke personer, som allerede havde opnået lovligt ophold og bopælsadresse inden den 1. september 2015. Med dette lovforslag udvides målgruppen, så både personer, der allerede i dag modtager uddannelses- eller kontanthjælp, og personer, der ansøger herom, fremover vil modtage integrationsydelse, hvis ikke de opfylder kravet om som minimum at have opholdt sig i Danmark i sammenlagt 7 ud af de seneste 8 år. Målgruppen omfatter både udlændinge og danske statsborgere.\n\nDet foreslås, at loven træder i kraft den 1. april 2016 og får virkning for ret til uddannelseshjælp, kontanthjælp og integrationsydelse pr. 1. juli 2016.\n"
962,0.854786,L 217,Forslag til lov om ændring af lov om integrationsgrunduddannelse (igu) og lov om Arbejdsgivernes Uddannelsesbidrag. (Videreførelse af igu-ordningen og egu-bonusordningen).,"Lovforslaget udmønter trepartsaftalen af 25. februar 2019 mellem regeringen (Venstre, Liberal Alliance og Det Konservative Folkeparti) og arbejdsmarkedets parter om forlængelse af integrationsgrunduddannelsen (igu) i en 3-årig periode. \n\nI 2016 indgik regeringen og arbejdsmarkedets parter en trepartsaftale om integration af flygtninge og familiesammenførte. Aftalen havde bl.a. som mål at støtte virksomhederne og kommunerne med at få hver anden flygtning og familiesammenført i arbejde efter 3 års ophold i landet. \n\nIntegrationsgrunduddannelsen (igu) var en 3-årig forsøgsordning, der kombinerer praktisk oplæring i en virksomhed og skoleundervisning med faglig opkvalificering og danskuddannelse, og skulle fungere som trædesten til beskæftigelse på almindelige arbejdsmarkedsvilkår. Regeringen foreslår med lovforslaget, at igu-ordningen forlænges til og med den 30. juni 2022 med mindre justeringer i bl.a. adgangen til aftalebaseret forlængelse ved barsel eller længerevarende sygdom og i refusion af udgifter til kost og logi."
764,0.854388,L 225,"Forslag til lov om ændring af lov om danskuddannelse til voksne udlændinge m.fl. (Indførelse af deltagerbetaling for danskuddannelse til udenlandske arbejdstagere, studerende m.v.).","Lovforslaget indfører deltagerbetaling for danskuddannelse for de såkaldte S-kursister, dvs. udenlandske arbejdstagere, EU-borgere, studerende m.fl. Deltagerbetalingen fastsættes til 2.000 kr. pr. modul. Lovforslaget bemyndiger udlændinge- og integrationsministeren til at fastsætte de nærmere regler om opkrævning og administration af deltagerbetalingen.\n\nHerudover udvider lovforslaget definitionen af S-kursister til også at omfatte ægtefæller og faste samlevende til udlændinge, der har været ansat ved en herværende international organisation m.v., som ved pensionering meddeles opholdstilladelse i Danmark.\n\nLovforslaget er del i udmøntningen af aftalen mellem regeringen (Venstre, Liberal Alliance og Konservative Folkeparti)og Dansk Folkeparti den 6. februar 2018 ""Aftale om lavere skat på arbejdsindkomst og større fradrag for pensionsindbetalinger""."
886,0.853097,L 135,"Forslag til lov om ændring af lov om social pension og lov om højeste, mellemste, forhøjet almindelig og almindelig førtidspension m.v. (Forhøjelse af satser for folkepension, forhøjelse af fradragsbeløb for folkepension og førtidspension og forhøjelse af fradragsbeløb for ægtefælles eller samlevers indkomst).","Loven består af fire hovedelementer: \n\n- Et direkte løft af folkepension og løft af fradragsbeløb for folke- og førtidspension efter gammel ordning. \n- Midlertidig forhøjelse af fradragsgrænser for pensionstillæg og ældrecheck m.v. \n- Forhøjelse af bundfradraget for folkepensionisters arbejdsindkomst. \n- Lempet aftrapning som følge af ægtefællers eller samlevers indkomst. \n\nMed loven løftes folkepensionsydelserne – grundbeløb, pensionstillæg og supplerende pensionsydelse, (ældrecheck) – i 2019 med ekstra 0,2 pct. point i forhold til 2018. Fradragsgrænserne for folkepension (som også gælder for førtidspension med tilkendelser før 2003) løftes tilsvarende. \n\nLoven indebærer desuden, at fradragsbeløbet i indtægtsgrundlaget før indtægtsregulering af pensionstillægget samt fradragsbeløbet i indtægtsgrundlaget før fastsættelse af den personlige tillægsprocent, der ligger til grund for udbetaling af den supplerende pensionsydelse (ældrechecken), helbredstillægget, varmetillægget og mediechecken, begge forhøjes med 15.000 kr. for enlige og med 30.000 kr. for par i 2019. Formålet hermed er at gøre det mere attraktivt for pensionister at fastholde en tilknytning til arbejdsmarkedet. Forhøjelsen aftrappes over 15 år. \n\nLoven har til formål at tilskynde folkepensionister til at arbejde mere. Derfor foreslås det, at bundfradraget for folkepensionisters indtægt ved personligt arbejde forhøjes fra 60.000 kr. til 100.000 kr. om året. \n\nLoven har yderligere det formål at øge tilskyndelsen til beskæftigelse for ikkepensionerede gifte/samlevende med en pensionist, idet aftrapningen lempes for folkepensionister og førtidspensionister på gammel ordning (med tilkendelser før 2003), der er gift/samlevende med en ikkepensionist. På den baggrund øges det gældende fradrag i indtægtsgrundlaget for den sociale pension som følge af en ikkepensioneret ægtefælle/samlevers indkomst. For folkepensionister og førtidspensionister på gammel ordning hæves det maksimale fradrag i indtægtsgrundlaget med 40.000 kr. i 2019-niveau. \n\nFor at øge rådighedsbeløbet og lempe aftrapningen for førtidspensionister på ny ordning (tilkendelser efter 2003) øges fradraget for ægtefælles/samlevers indkomst ligeledes med 40.000 kr. i 2019-niveau.\n"

In [148]:
# Retrieve the top 10 most similar cases of title embeddings

import numpy as np

top_k = 10

top_indices = np.argsort(
    similarities_titles[0]
)[::-1][:top_k]

results_title = df_cases.iloc[top_indices].copy()
    
results_title["similarity"] = similarities_titles[0][top_indices]

results_title[
    [
        "similarity",
        "sag_nummer",
        "sag_titel",
        "sag_resume",
    ]
]

,similarity,sag_nummer,sag_titel,sag_resume
314,0.858934,L 188,Forslag til lov om integrationsgrunduddannelse (igu).,"Lovforslaget udmønter den del af trepartsaftalen om arbejdsmarkedsintegration mellem regeringen og arbejdsmarkedets parter af 17. marts 2016, der angår oprettelse af en ny integrationsgrunduddannelse (igu). \n\nMed den foreslåede integrationsgrunddannelse får flygtninge og familiesammenførte adgang til både praktisk oplæring på en virksomhed (som aflønnes med elevløn) og til offentligt betalt skoleundervisning med faglig opkvalificering og danskuddannelse og bliver samtidig selvforsørgende i et ustøttet ansættelsesforhold. I forhold til integrationslovens eksisterende virksomhedsrettede redskaber (løntilskud og virksomhedspraktik) udgør integrationsgrunduddannelsen en væsentlig mindre bureaukratisk ordning for både virksomhed, udlænding og kommune, idet virksomhed og udlænding selv aftaler ansættelsesforholdet uden kommunens mellemkomst. Virksomheder, der etablerer og gennemfører integrationsgrunddannelser, bliver tilgodeset med en bonus. Integrationsuddannelsen indføres som en 3-årig forsøgsordning.\n \nAftalen med arbejdsmarkedets parter, som lovforslaget udmønter, forudsætter igangsættelse af integrationsgrunddannelsen pr. 1. juli 2016.\n\n"
315,0.854428,L 189,Forslag til lov om ændring af integrationsloven og forskellige andre love. (Bedre rammer for at modtage og integrere flygtninge og styrket virksomhedsrettet integrationsprogram m.v.).,"Lovforslaget har til formål at udmønte hovedparten af de dele af aftalen »Bedre rammer for at modtage og integrere flygtninge«, som regeringen har indgået med KL, og de dele af »Trepartsaftale om arbejdsmarkedsintegration«, som regeringen har indgået med arbejdsmarkedets parter, som kræver lovændringer. \n\nLovforslaget indeholder bl.a. ændringer af integrationslovens regler om boligplacering af flygtninge og en målretning af programmet mod beskæftigelse i kraft af en mere virksomhedsrettet indsats og ændringer af finansieringsreglerne, så finansieringen målrettes mod de kommuner, som modtager flest flygtninge, og de kommuner og virksomheder, som leverer de bedste integrationsresultater, samt regelforenklinger på en række områder. Desuden er der forslag om ændringer af danskuddannelsesloven, almenboligloven og almenlejeloven. Herudover indeholder lovforslaget ændringer af friskoleloven og lov om efterskoler og frie fagskoler.\n\nDerudover indeholder lovforslaget ændringer af dagtilbudsloven, idet kommunerne med forslaget i en midlertidig periode på 2 år gives øget mulighed for med udgangspunkt i det enkelte barns behov for sprogstimulering selv at fastsætte omfanget af sprogstimuleringen til en nærmere defineret gruppe af tosprogede børn, der ikke går i dagtilbud."
612,0.853388,L 97,Forslag til lov om ændring af integrationsloven og lov om danskuddannelse til voksne udlændinge m.fl. (Forenkling og justering af reglerne om fordeling og boligplacering af flygtninge og præcisering af personkreds for danskuddannelse m.v.).,"Regeringen ønsker med lovforslaget at forenkle kvotefordelingsreglerne til fordeling af flygtninge mellem kommunerne. Ændringerne er foranlediget af de meget store udsving i landstallet, som man har oplevet de senere år. Det har skabt ønske om en enklere fordelingsmodel. De enkelte dele af forslaget har været drøftet med KL.\n\nDerudover ændrer lovforslaget reglerne om boliganvisning efter integrationsloven, så der ikke kan opnås fordele ved at ændre opholdsgrundlag fra familiesammenført til flygtning. Samtidig tydeliggøres det, at en tilflytningskommune ikke er forpligtet til at anvise en bolig, hvis en flygtning fraflytter den kommune, vedkommende er visiteret til. \n\nLovforslaget ændrer samtidig reglerne i lov om danskuddannelse til voksne udlændinge m.fl., så disse sidestilles med S-kursister (nyankomne udenlandske arbejdstagere m.m.). Danskuddannelsen vil således være omfattet af reglerne om betaling af depositum og reglerne om klippekort.\n"
240,0.852751,L 111,"Forslag til lov om ændring af lov om aktiv socialpolitik, integrationsloven og forskellige andre love. (Udvidelse af personkredsen for modtagelse af integrationsydelse m.v.).","Med lovforslaget foreslås det, at målgruppen for integrationsydelsen udvides til at omfatte alle personer, som ikke har opholdt sig i Danmark i mindst 7 ud af de seneste 8 år. Formålet med udvidelsen er at styrke målgruppens incitament til at komme i arbejde og blive selvforsørgende og blive integreret i det danske samfund.\n\nFolketinget indførte ved lov nr. 1000 af 30. august 2015 et opholdskrav for ret til uddannelseshjælp og kontanthjælp og en ny, lavere integrationsydelse for personer, der ikke opfylder dette opholdskrav. Loven omfatter ikke personer, som allerede havde opnået lovligt ophold og bopælsadresse inden den 1. september 2015. Med dette lovforslag udvides målgruppen, så både personer, der allerede i dag modtager uddannelses- eller kontanthjælp, og personer, der ansøger herom, fremover vil modtage integrationsydelse, hvis ikke de opfylder kravet om som minimum at have opholdt sig i Danmark i sammenlagt 7 ud af de seneste 8 år. Målgruppen omfatter både udlændinge og danske statsborgere.\n\nDet foreslås, at loven træder i kraft den 1. april 2016 og får virkning for ret til uddannelseshjælp, kontanthjælp og integrationsydelse pr. 1. juli 2016.\n"
1756,0.851999,L 82,Forslag til lov om ændring af lov om integrationsgrunduddannelse (igu) og lov om Arbejdsgivernes Uddannelsesbidrag. (Videreførelse og udvidelse af igu-ordningen og videreførelse af egu-fgu-bonusordningen).,"Formålet med forslaget er at videreføre og udvide integrationsgrunduddannelsesordningen (igu). Forslaget indebærer, at igu-ordningen og egu-bonussen videreføres i 4 år frem til den 31. december 2027. Forslaget bygger på en aftale mellem regeringen (Socialdemokratiet, Venstre og Moderaterne) og arbejdsmarkedets parter på baggrund af en anbefaling fra Reformkommissionen. \n\nDerudover indebærer forslaget, at persongruppen, som har adgang til ordningen, udvides til at omfatte alle former for familiesammenførte i alderen 18-40 år, som har været i Danmark i op til 20 år. I forlængelse heraf indføres der et årligt loft over antallet af nye igu-forløb på 1.500, hvor der efter behov og nærmere drøftelse i aftalekredsen kan indføres et midlertidigt stop, når der i det enkelte år er påbegyndt 1.200 igu-forløb. Forslaget vil endvidere give udlændinge- og integrationsministeren mulighed for at fastsætte nærmere regler for udstedelse af beviser til fuldførte og delvis gennemførte igu-forløb. \n\nForslaget indebærer også, at egu-fgu-bonusordningen forlænges med 4 år. \n\nDet foreslås, at loven træder i kraft den 1. januar 2024.\n"
962,0.851149,L 217,Forslag til lov om ændring af lov om integrationsgrunduddannelse (igu) og lov om Arbejdsgivernes Uddannelsesbidrag. (Videreførelse af igu-ordningen og egu-bonusordningen).,"Lovforslaget udmønter trepartsaftalen af 25. februar 2019 mellem regeringen (Venstre, Liberal Alliance og Det Konservative Folkeparti) og arbejdsmarkedets parter om forlængelse af integrationsgrunduddannelsen (igu) i en 3-årig periode. \n\nI 2016 indgik regeringen og arbejdsmarkedets parter en trepartsaftale om integration af flygtninge og familiesammenførte. Aftalen havde bl.a. som mål at støtte virksomhederne og kommunerne med at få hver anden flygtning og familiesammenført i arbejde efter 3 års ophold i landet. \n\nIntegrationsgrunduddannelsen (igu) var en 3-årig forsøgsordning, der kombinerer praktisk oplæring i en virksomhed og skoleundervisning med faglig opkvalificering og danskuddannelse, og skulle fungere som trædesten til beskæftigelse på almindelige arbejdsmarkedsvilkår. Regeringen foreslår med lovforslaget, at igu-ordningen forlænges til og med den 30. juni 2022 med mindre justeringer i bl.a. adgangen til aftalebaseret forlængelse ved barsel eller længerevarende sygdom og i refusion af udgifter til kost og logi."
765,0.850826,L 231,"Forslag til lov om ændring af udlændingeloven. (Reform af reglerne om ægtefællesammenføring med nyt integrationskrav i stedet for tilknytningskravet, skærpet boligkrav m.v.).","Formålet med lovforslaget er at stramme ægtefællesammenføringsreglerne, bl.a. ved at styrke fokus på, om begge ægtefæller har udsigt til en vellykket integration i Danmark.\n\nMed lovforslaget erstattes det gældende tilknytningskrav med et integrationskrav. Integrationskravet medfører, at ægtefællesammenføring som hovedregel kun kan gives, hvis den herboende ægtefælle har sprogkundskaber, der svarer til Prøve i Dansk 3, og hvis ægtefællerne samlet set opfylder tre ud af fem øvrige betingelser vedrørende sprogkundskaber, erhvervserfaring og uddannelse. \n\nLovforslaget viderefører de hidtidige regler om, at ægtefællesammenføring normalt kun kan gives, hvis den ægtefælle, der kommer hertil, har haft mindst ét lovligt ophold i Danmark. Derudover skærpes de overførte betingelser i reglerne om ægtefællesammenføring, så de svarer til reglerne for tidsubegrænset opholdstilladelse.\n\nLovforslaget indeholder desuden en skærpelse af boligkravet. Boligen må fremover ikke ligge i bestemte boligområder, som optages på boligkravslisten for ægtefællesammenføring. Udlændinge- og integrationsministeren fastsætter de nærmere regler om kriterierne for optagelse af boligområder på listen og offentliggør, hvilke boligområder der er omfattet af boligkravslisten for ægtefællesammenføring. \n\nDen økonomiske sikkerhedsstillelse ved ægtefællesammenføring hæves til 100.000 kr. (i 2018-niveau) mod i dag 50.000 kr. (55.375,27 kr. i 2018-niveau), og reglerne om gradvis nedsættelse af sikkerhedsstillelsen justeres.\n\nDerudover udvides sprogkravet til den ægtefælle, der kommer hertil, så man fremover udover at bestå en danskprøve på A1-niveau inden 6 måneder også skal bestå en danskprøve på A2-niveau eller lignende senest 9 måneder efter tilmelding til folkeregisteret eller fra meddelelse af tilladelse til familiesammenføring.\n\nLovforslaget er en del af udmøntningen af aftalen af 7. februar 2018 mellem regeringen (Venstre, Liberal Alliance og Konservative Folkeparti), Dansk Folkeparti og Socialdemokratiet om stramme, afbalancerede og realistiske regler for ægtefællesammenføring, hvor integrationen er i centrum."
317,0.849878,L 191 B,"Forslag til lov om ændring af lov om ændring af lov om aktiv socialpolitik, integrationsloven og forskellige andre love. (Overgangsregel for ret til ferie for uddannelseshjælps- og kontanthjælpsmodtagere, der overgår til integrationsydelse).\r\n","Lovforslaget er en del af det tidligere L 191, der blev delt ved andenbehandlingen. \n\nMed lovforslaget bliver det foreslået, at kontanthjælps-, og uddannelseshjælpsmodtagere, der overgår til integrationsydelse, får lov til at afholde deres allerede optjente ferie. \n\nLovforslaget træder i kraft dagen efter bekendtgørelsen i Lovtidende."
1326,0.849399,L 202,Forslag til lov om ændring af lov om integrationsgrunduddannelse (igu). (Udvidelse af målgruppen m.v. for integrationsgrunduddannelsen).,"Det foreslås med lovforslaget, at opholdsbetingelsen for integrationsuddannelsesforløb udvides med 5 år, således at flygtninge og familiesammenførte til flygtninge, som har været i Danmark i 0-10 år, fremover får mulighed for at tage et integrationsgrunduddannelsesforløb. Derudover foreslås det, at omfanget af uddannelse i form af amu og sprogkurser udvides med 3 uger, hvorved der samlet set vil være 23 ugers uddannelse i et samlet integrationsgrundsuddannelsesforløb. \n\nLovforslaget udmønter dele af trepartsaftalen af 21. december 2020 mellem regeringen (Socialdemokratiet) og arbejdsmarkedets parter om at udvide og forbedre integrationsuddannelsesforløb.\n\nDet foreslås, at loven træder i kraft den 1. maj 2021, og at de foreslåede regler alene gælder for integrationsgrunduddannelsesforløb, der påbegyndes den 1. maj 2021 eller senere.\n"
204,0.848951,L 75,Forslag til lov om ændring af integrationsloven og lov om planlægning. (Midlertidig indkvartering af flygtninge).\r\n,"Med lovforslaget får udlændinge-, integrations- og boligministeren hjemmel til at fastsætte nærmere regler om anvisning af et midlertidigt opholdssted til flygtninge. Det er hensigten med bemyndigelsen at fastsætte regler om, at en enlig flygtning efter en konkret og individuel vurdering af flygtningens behov sammenholdt med indkvarteringens beskaffenhed vil kunne anvises til at dele et beboelsesrum med en eller flere andre enlige flygtninge som en midlertidig indkvarteringsløsning. \n\nLovforslaget indebærer endvidere, at det bliver gjort muligt for kommunerne at fravige de vejledende grænseværdier for støj, som følger af Miljøstyrelsens vejledninger, hvilket indebærer, \nat der kan etableres midlertidige opholdssteder for flygtninge på støjbelastede arealer. \n\nForslaget ønskes hastebehandlet.\n\nLovforslaget udmønter dele af regeringens asyludspil.\n\n"

# Building a dataset with the top 10 for each candidate questions

In [150]:
question_texts = [
    f"query: {question}"
    for question in df_questions["Question"]
]

question_embeddings = model.encode_query(
    question_texts,
    normalize_embeddings=True,
    show_progress_bar=True,
)

Batches: 100%|██████████| 5/5 [00:01<00:00,  3.37it/s]

In [151]:
similarities = question_embeddings @ case_embeddings_texts.T

similarities.shape

(136, 2128)

In [152]:
# Build the actual evaluation dataset:

import numpy as np
import pandas as pd

top_k = 10

rows = []

for question_idx in range(len(df_questions)):

    scores = similarities[question_idx]

    top_indices = np.argsort(scores)[::-1][:top_k]

    question = df_questions.iloc[question_idx]

    for rank, case_idx in enumerate(top_indices, start=1):

        case = df_cases.iloc[case_idx]

        rows.append({
            "question": question["Question"],
            "election": question["election"],
            "rank": rank,
            "similarity": scores[case_idx],

            "sagid": case["sagid"],
            "sag_nummer": case["sag_nummer"],
            "sag_titel": case["sag_titel"],
            "sag_resume": case["sag_resume"],

            "relevance": None,
            "notes": None,
        })

df_evaluation = pd.DataFrame(rows)

In [154]:
evaluation_file = DATA_DIR / "evaluation" / "e5_top10_relevance.csv"

evaluation_file.parent.mkdir(
    parents=True,
    exist_ok=True
)

df_evaluation.to_csv(
    evaluation_file,
    index=False,
    encoding="utf-8-sig"
)

print(f"Saved to: {evaluation_file}")

Saved to: ..\data\temp_data\evaluation\e5_top10_relevance.csv

Given a candidate-test question, does E5 retrieve parliamentary cases that are actually relevant to the political issue expressed by that question?
I will manually evaluate the data using 0 - 2 score. 0 = Not relevant, 1 = Partially relevant, 2 = Clearly relevant.