# Find topics in ODA

In [13]:
import requests
import pandas as pd
from pathlib import Path
import requests

In [14]:
DATA_DIR = Path("../data/temp_data")

roll_calls_file = DATA_DIR / "parliament" / "roll_calls_resume.csv"

df_roll_calls = pd.read_csv(roll_calls_file)

df_cases = (
    df_roll_calls[
        [
            "sagid",
            "sag_nummer",
            "sag_titel",
            "sag_titelkort",
            "sag_resume",
            "dato",
        ]
    ]
    .drop_duplicates(subset="sagid")
    .reset_index(drop=True)
)

print("Unique parliamentary cases:", len(df_cases))
df_cases.head()

Unique parliamentary cases: 2128

,sagid,sag_nummer,sag_titel,sag_titelkort,sag_resume,dato
0,1449,L 200,Forslag til lov om ændring af virksomhedsskatt...,Om indgreb mod utilsigtet udnyttelse af virkso...,Loven ændrer virksomhedsskatteordningens regle...,2014-09-09 09:15:00
1,12715,L 4,Forslag til lov om ændring af lov om afgift af...,Om tilbagerulning af forsyningssikkerhedsafgif...,"Lovforslaget betyder, at afgiftsforhøjelserne ...",2014-10-31 10:00:00
2,13015,L 33,Forslag til lov om ændring af lov om produktio...,Om kompetencebevis.,"Lovforslaget indebærer, at ordningen med, at a...",2014-12-02 13:00:00
3,13004,L 19,Forslag til lov om dansk turisme.,Om dansk turisme.,Lovforslaget etablerer et nationalt turismefor...,2014-12-02 13:00:00
4,12991,L 13,Forslag til lov om ændring af lov om aktiv soc...,Om ændring af formue- og fradragsregler ved ef...,"Formålet med lovforslaget er at sikre, at pers...",2014-12-04 10:00:00

In [8]:
url = "https://oda.ft.dk/api/EmneordSag"

rows = []
next_url = url

while next_url:
    response = requests.get(next_url)
    response.raise_for_status()

    data = response.json()
    rows.extend(data["value"])

    next_url = data.get("odata.nextLink") or data.get("@odata.nextLink")

df_emneord_sag = pd.DataFrame(rows)

print(df_emneord_sag.shape)
df_emneord_sag.head()

(275173, 4)

     id  emneordid  sagid          opdateringsdato
0   749        387    370   2014-08-11T13:23:02.27
1   750        387    371   2014-08-11T13:23:02.52
2   752        226    373  2014-08-11T13:23:04.003
3  8706       2554    574  2014-08-11T19:16:40.833
4  8849        387   4006  2014-08-11T19:19:51.583

In [9]:
df_emneord_sag.columns

Index(['id', 'emneordid', 'sagid', 'opdateringsdato'], dtype='object')

In [10]:
url = "https://oda.ft.dk/api/Emneord"

rows = []
next_url = url

while next_url:
    response = requests.get(next_url)
    response.raise_for_status()

    data = response.json()
    rows.extend(data["value"])

    next_url = data.get("odata.nextLink") or data.get("@odata.nextLink")

df_emneord = pd.DataFrame(rows)

print(df_emneord.shape)
print(df_emneord.columns)

df_emneord.head()

(49227, 4)
Index(['id', 'typeid', 'emneord', 'opdateringsdato'], dtype='object')

,id,typeid,emneord,opdateringsdato
0,1,1,økonomisk redegørelse,2014-12-16T18:44:04.673
1,2,3,Grønland,2014-10-06T09:34:14.377
2,3,4,Retspleje 24,2015-04-21T15:30:57.71
3,4,1,efterretningstjeneste og sikkerhedspolitik,2014-08-11T12:53:19.827
4,5,3,narkotika,2014-08-11T12:53:21.013

In [11]:
df_emneord_full = df_emneord_sag.merge(
    df_emneord,
    left_on="emneordid",
    right_on="id",
    how="left",
    suffixes=("_relation", "_emneord")
)

df_emneord_full.head()

,id_relation,emneordid,sagid,opdateringsdato_relation,id_emneord,typeid,emneord,opdateringsdato_emneord
0,749,387,370,2014-08-11T13:23:02.27,387,1,Tingdok,2014-08-11T12:57:37.433
1,750,387,371,2014-08-11T13:23:02.52,387,1,Tingdok,2014-08-11T12:57:37.433
2,752,226,373,2014-08-11T13:23:04.003,226,1,Statsrevisorerne,2014-08-11T13:23:04.003
3,8706,2554,574,2014-08-11T19:16:40.833,2554,2,miljøudvalget,2014-08-11T19:16:40.833
4,8849,387,4006,2014-08-11T19:19:51.583,387,1,Tingdok,2014-08-11T12:57:37.433

In [15]:
relevant_sagids = set(df_cases["sagid"])

df_emneord_relevant = df_emneord_full[
    df_emneord_full["sagid"].isin(relevant_sagids)
].copy()

In [16]:
print("Relations:", len(df_emneord_relevant))
print(
    "Cases with at least one emneord:",
    df_emneord_relevant["sagid"].nunique()
)
print(
    "Unique emneord:",
    df_emneord_relevant["emneord"].nunique()
)

Relations: 7688
Cases with at least one emneord: 2128
Unique emneord: 884

In [17]:
df_emneord_relevant["typeid"].value_counts().sort_index()

typeid
1    2286
2      39
3    1298
4    4065
Name: count, dtype: int64

In [18]:
url = "https://oda.ft.dk/api/Emneordstype"

data = requests.get(url).json()

df_emneordstype = pd.DataFrame(data["value"])

df_emneordstype

   id           type          opdateringsdato
0   1     Sagsområde  2015-05-27T13:48:24.487
1   2  Ukontrolleret  2015-06-04T08:30:36.683
2   3   Kontrolleret  2015-05-27T13:48:24.487
3   4    Lovsagsnavn   2015-06-08T15:13:27.44
4   5      Thesaurus  2014-08-06T14:43:17.187
5   6    Kontonummer  2014-08-06T14:43:17.187
6   7   Retsgrundlag  2014-08-06T14:43:17.187

In [19]:
type_counts = (
    df_emneord_relevant
    .groupby("typeid")
    .agg(
        relations=("sagid", "size"),
        cases=("sagid", "nunique"),
        unique_emneord=("emneord", "nunique")
    )
    .reset_index()
)

type_counts = type_counts.merge(
    df_emneordstype[["id", "type"]],
    left_on="typeid",
    right_on="id",
    how="left"
)

type_counts[
    ["typeid", "type", "relations", "cases", "unique_emneord"]
]

   typeid           type  relations  cases  unique_emneord
0       1     Sagsområde       2286   2128             254
1       2  Ukontrolleret         39     29              28
2       3   Kontrolleret       1298    555             317
3       4    Lovsagsnavn       4065   1889             289

In [20]:
df_sagsomraade = df_emneord_relevant[
    df_emneord_relevant["typeid"] == 1
].copy()

df_sagsomraade["emneord"].value_counts().head(50)

emneord
strafferet og kriminalitet                        63
COVID-19 pandemien                                60
finansiel virksomhed                              42
finanspolitik                                     42
EU                                                41
retspleje og domstole                             41
folkeskolen                                       41
erhvervsdrivende virksomhed                       40
alternative og vedvarende energikilder            36
energiforsyning                                   33
personskatter                                     33
indvandrere og integration                        32
arbejdsløshedsforsikring og dagpenge              32
indfødsrets og naturalisering                     31
miljøpolitik og miljøbeskyttelse                  29
social service                                    28
boligpolitik                                      28
flygtninge og asylansøgere                        28
dyr og dyrevelfærd                                26
familieret                                        25
gymnasiale uddannelser                            24
sundhedsfremme og sygdomsforebyggelse             24
motorkøretøjer                                    23
energiafgifter                                    23
arbejdsmarkedspolitik og beskæftigelsesindsats    23
politi og retsvæsen                               23
erhvervsuddannelser                               22
voksen- og efteruddannelse                        21
international beskatning                          21
færdselsret                                       21
aktiv beskæftigelsesindsats                       21
moms                                              20
arbejdsmarkedspolitik og beskæftigelsespolitik    20
ophold og visum                                   20
kommuner                                          19
inddrivelse                                       19
vejinfrastruktur                                  19
socialpolitik                                     18
naturbeskyttelse og kystsikring                   18
politi og våben                                   18
lægemidler og apoteker                            17
kriminalforsorg og afsoning                       17
skattekontrol                                     17
jernbaneinfrastruktur                             17
energipolitik og energieffektivitet               16
frie grundskoler                                  16
valg og folkeafstemninger                         16
videregående uddannelse                           15
selskaber og fonde                                15
folkepension og førtidspension                    15
Name: count, dtype: int64

In [21]:
print(
    "Cases with Sagsområde:",
    df_sagsomraade["sagid"].nunique(),
    "/",
    df_cases["sagid"].nunique()
)

print(
    "Unique Sagsområder:",
    df_sagsomraade["emneord"].nunique()
)

Cases with Sagsområde: 2128 / 2128
Unique Sagsområder: 254

Sagsområde has 100% coverage of the 2,128 parliamentary cases, and it is clearly intended to describe subject areas. More importantly, the examples look substantively useful: 

*strafferet og kriminalitet, finanspolitik, indvandrere og integration, socialpolitik, energipolitik og energieffektivitet*, etc.

But there's one important complication: 254 Sagsområder is still quite granular, and some appear semantically overlapping:

*arbejdsmarkedspolitik og beskæftigelsesindsats
arbejdsmarkedspolitik og beskæftigelsespolitik
aktiv beskæftigelsesindsats*


So, we have discovered an official controlled starting vocabulary that may allow us to construct broader political topics much more defensibly.

In [22]:
sagsomraader_per_case = (
    df_sagsomraade
    .groupby("sagid")["emneord"]
    .nunique()
)

print(sagsomraader_per_case.value_counts().sort_index())

emneord
1    1985
2     130
3      11
4       2
Name: count, dtype: int64

In [23]:
multi_sagsomraade_ids = sagsomraader_per_case[
    sagsomraader_per_case > 1
].index

df_multi_sagsomraade = (
    df_sagsomraade[
        df_sagsomraade["sagid"].isin(multi_sagsomraade_ids)
    ]
    .groupby("sagid")["emneord"]
    .apply(list)
    .reset_index()
)

df_multi_sagsomraade = df_multi_sagsomraade.merge(
    df_cases[["sagid", "sag_nummer", "sag_titel"]],
    on="sagid",
    how="left"
)

df_multi_sagsomraade[
    ["sag_nummer", "sag_titel", "emneord"]
].head(20)

,sag_nummer,sag_titel,emneord
0,L 9,"Forslag til lov om ændring af momsloven, skatt...","[moms , skattekontrol]"
1,L 10,Forslag til lov om ændring af aktieavancebeska...,"[beskatning af aktier, moms , selskabsskatter ..."
2,L 41,"Forslag til lov om ændring af ligningsloven, f...","[fonds- og foreningsbeskatning, inddrivelse]"
3,L 56,Forslag til lov om ændring af lov om Arbejdsgi...,"[erhvervsuddannelser, uddannelsesstøtte]"
4,L 85,Forslag til lov om ændring af lov om råstoffer...,"[naturbeskyttelse og kystsikring, råstoffer og..."
5,L 103,Forslag til lov om ændring af forældreansvarsl...,"[familieret, udsatte børn og unge]"
6,L 112,Forslag til lov om ændring af lov om jordbruge...,"[landbrug, natur og miljø]"
7,L 130,Forslag til lov om kommunale internationale gr...,"[folkeskolen, frie grundskoler]"
8,L 120,Forslag til lov om ændring af lov om social se...,"[social service, udsatte børn og unge]"
9,L 144,Forslag til lov om ændring af lov om afgift af...,"[energiafgifter , moms ]"
10,L 159,Forslag til lov om ændring af lov om kommunal ...,"[færgefart, kommuner]"
11,L 172,"Forslag til lov om ændring af selskabsloven, l...","[erhvervsdrivende virksomhed, finansiel virkso..."
12,L 29,Forslag til lov om omdannelse af retsforbehold...,"[afstemninger, forbehold, retlige anliggender]"
13,L 6,Forslag til lov om ændring af forskellige lovb...,"[familieret, socialforvaltning og retssikkerhed]"
14,L 47,Forslag til lov om ændring af lov om social se...,[praksissektoren og kommunale sundhedsordninge...
15,L 79,Forslag til lov om ændring af lov om fuldbyrde...,"[kriminalforsorg og afsoning, PET og terrorbek..."
16,L 78,Forslag til lov om ændring af retsplejeloven. ...,"[kriminalforsorg og afsoning, PET og terrorbek..."
17,L 87,Forslag til lov om ændring af udlændingeloven....,"[familiesammenføring, flygtninge og asylansøgere]"
18,L 155,Forslag til lov for Grønland om kontrol med de...,"[råstoffer og udvinding, sundhed og sociale fo..."
19,L 154,Forslag til lov om ændring af lov om byfornyel...,"[boligpolitik, byfornyelse]"

In [24]:
sagsomraader = sorted(
    df_sagsomraade["emneord"].unique()
)

[x for x in sagsomraader if "integr" in x.lower()]

['indvandrere og integration']

In [25]:
[x for x in sagsomraader if "social" in x.lower()]

['social service',
 'sociale forhold',
 'sociale ydelser',
 'socialforvaltning og retssikkerhed',
 'socialpolitik',
 'sundhed og sociale forhold']

In [28]:
print(sagsomraader_per_case.value_counts().sort_index())

df_sagsomraade_vocab = (
    df_sagsomraade
    .groupby("emneord")
    .agg(
        n_cases=("sagid", "nunique")
    )
    .reset_index()
    .sort_values("emneord")
    .reset_index(drop=True)
)

pd.set_option("display.max_rows", 300)

df_sagsomraade_vocab

emneord
1    1985
2     130
3      11
4       2
Name: count, dtype: int64

                                               emneord  n_cases
0                                   COVID-19 pandemien       60
1                                                  DSB        4
2                                               Danida        1
3                                   Danmarks Statistik        1
4                                   Det Økonomiske Råd        3
5                                                   EU       41
6                                     Flygtningenævnet        1
7                                                 NATO        1
8                              PET og terrorbekæmpelse       12
9                                           Statens it        1
10                                    Udlændingenævnet        2
11                                 Udlændingestyrelsen        7
12                                      administration        3
13                                affald og kemikalier        9
14                                affald og renovation        3
15                        afgift af dødsboer og gaver         3
16                                        afstemninger        1
17                         aktiv beskæftigelsesindsats       21
18                         aktivering og jobformidling        4
19              alternative og vedvarende energikilder       36
20                arbejdsløshedsforsikring og dagpenge       32
21                                arbejdsmarkedsbidrag        3
22                            arbejdsmarkedspensioner        12
23      arbejdsmarkedspolitik og beskæftigelsesindsats       23
24      arbejdsmarkedspolitik og beskæftigelsespolitik       20
25                           arbejdsmarkedsuddannelser        1
26                       arbejdsmiljø og arbejdsskader       13
27                        arbejdsret og overenskomster        8
28                      arkiver, biblioteker og museer        6
29                                              barsel        1
30                         beredskab og civile opgaver        6
31                                beskatning af aktier        9
32                         beskatning af fast ejendom        15
33                              bestyrelser og ledelse        2
34                      biskopper, provster og præster        1
35                                             boliger        2
36                         boliger til særlige grupper        3
37                                        boligpolitik       28
38                                         byfornyelse        7
39                                             byggeri       10
40                                 byråd og regionsråd        1
41                                børne- og ungeydelse        3
42                                        børnetilskud        1
43                                            civilret       14
44             cybersikkerhed og informationssikkerhed        3
45                                  dag- og klubtilbud        2
46                                           dagtilbud       13
47                         databeskyttelse og dataetik        3
48           digital service og digital transformation        3
49                                      digitalisering        6
50                                  dyr og dyrevelfærd       26
51                                          dødsboskat        1
52                                efterløn og fleksjob        5
53          efterretningstjeneste og sikkerhedspolitik        6
54                                        ejendomsdata        5
55                              ejer- og andelsboliger        4
56                                         ejerboliger        3
57                                     energiafgifter        23
58                                     energiforsyning       33
59                                       energipolitik        2
60                 energipolitik og energieffektivitet       16
61                            erhverv og arbejdsmarked       12
62           erhvervsakademier og professionshøjskoler        5
63                         erhvervsdrivende virksomhed       40
64                                 erhvervsuddannelser       22
65                                   erhvervsudlejning        2
66                                   etik og forskning        8
67                                          familieret       25
68                                 familiesammenføring       10
69                                  faste forbindelser       10
70                                finansiel virksomhed       42
71                                 finansielle forhold        8
72                                       finanspolitik       42
73                                  fiskeri og havbrug        8
74                         fiskeri, fangst og landbrug        1
75                          flygtninge og asylansøgere       28
76                                         folkekirken        7
77                         folkeoplysning og højskoler        3
78                      folkepension og førtidspension       15
79                     folkeregistret og borgerservice        3
80                                         folkeskolen       41
81   folketingsarbejdet, grundloven og forretningso...        7
82                       fonds- og foreningsbeskatning        6
83                                           forbehold        3
84                         forebyggende ældreindsatser        1
85                            formueret og tinglysning        6
86                             forskning og innovation        8
87                                           forsvaret        3
88                       forvaltningsret og persondata       15
89                                fossile brændstoffer        1
90                                    frie grundskoler       16
91                                  fysisk planlægning       13
92                                         færdselsret       21
93                                           færgefart        4
94                                           fødevarer        4
95                fødevaresikkerhed og fødevarekontrol        1
96                                     geodata og kort        2
97                    ghettoer og udsatte boligområder        2
98                          gods- og erhvervstransport       10
99                                        grøn trepart        1
100                             gymnasiale uddannelser       24
101                                  handel og eksport       14
102                                       handicappede        1
103                                              havne        1
104                                       hjemmeværnet        2
105                                hjælp til pårørende        1
106                     hverv og økonomiske interesser        3
107                                        inddrivelse       19
108                      indfødsrets og naturalisering       31
109                                   indfødsretsprøve        4
110                         indvandrere og integration       32
111                          international beskatning        21
112           international ret og menneskerettigheder        4
113                             internationale forhold        5
114                      internationale organisationer        1
115                                it og teleforsyning        5
116              it-løsninger og digital infrastruktur        2
117                          jagt- og vildtforvaltning        5
118                              jernbaneinfrastruktur       17
119                            jord- og luftforurening        1
120                   kirkelige handlinger og ritualer        1
121                          klageforhold og klagenævn        3
122                       klageinstanser og klagesager        3
123                                              klima        1
124                  klimapolitik og klimaforandringer        3
125                                    klimatilpasning        1
126                                kollektiv transport        6
127                       kommunal og regional økonomi        7
128                                  kommunale skatter        1
129                                           kommuner       19
130                          kommuner og infrastruktur        3
131                   konkurrence- og forbrugerforhold       12
132                   kontanthjælp og uddannelseshjælp        4
133                        kriminalforsorg og afsoning       17
134                             kultur- og kunststøtte        1
135                      kulturarv og bygningsbevaring        5
136                    kulturelle og religiøse forhold        3
137                      kulturformidling og kulturliv        2
138                                kunstig befrugtning        5
139               kunstneriske og maritime uddannelser        2
140                           kunstneriske uddannelser        1
141                              kursgevinstbeskatning        3
142                kvalitetsstandarder på ældreområdet        1
143                      køn og ligestillingsvurdering        3
144                                           landbrug       13
145                                     landdistrikter        3
146                                        lejeboliger       13
147                                     ligebehandling        4
148                             ligestilling og barsel        4
149                                          lovudkast        1
150                                         lufttrafik        9
151                             lægemidler og apoteker       17
152                                      lønsumsafgift        1
153                                             medier       13
154                                       menighedsråd        4
155              menneskehandel og illegal indvandring        1
156                                  militært materiel        2
157                                              miljø        1
158                             miljø- og genteknologi        3
159                                      miljøafgifter        8
160                   miljøpolitik og miljøbeskyttelse       29
161                                     ministeransvar        4
162                                              moms        20
163                                     motorkøretøjer       23
164                                              musik        1
165                                     natur og miljø        1
166                    naturbeskyttelse og kystsikring       18
167                                 nordisk samarbejde        1
168                      offentlige data og datadeling        1
169                        olie- og naturgasindvinding        9
170                             omkostningsgodtgørelse        1
171                                          ophavsret        5
172                                    ophold og visum       20
173       partistøtte, partiregnskaber og gruppestøtte        1
174                            patent- og varemærkning        4
175             patientrettigheder og patientsikkerhed       11
176              pensions- og pensionsafkastbeskatning        7
177                                      personskatter       33
178                                politi og retsvæsen       23
179                                    politi og våben       18
180                                          postvæsen        2
181     praksissektoren og kommunale sundhedsordninger        8
182                   produktsikkerhed og autorisation        8
183                                          psykiatri       10
184                                      punktafgifter        5
185                                           regioner        3
186                               regnskab og revision        8
187                                    rejser og besøg        1
188                                retlige anliggender        1
189                              retspleje og domstole       41
190                           rygning og rusmiddelbrug       11
191                              råstoffer og skovbrug        1
192                             råstoffer og udvinding        1
193                                          satspulje        1
194                                         scenekunst        1
195                                 selskaber og fonde       15
196                                   selskabsskatter         8
197             selvstyreordningen og Rigsfællesskabet        4
198                                      skattekontrol       17
199                               skifteret og konkurs        6
200                                     social service       28
201                                    sociale forhold        1
202                                    sociale ydelser       14
203                 socialforvaltning og retssikkerhed        5
204                                      socialpolitik       18
205                                               spil        9
206                                     sport og idræt        3
207                         strafferet og kriminalitet       63
208                          studie- og ungdomsboliger        1
209                         sundhed og sociale forhold        9
210                                        sundheds it        2
211              sundhedsfremme og sygdomsforebyggelse       24
212                  sundhedspersonale og autorisation        6
213                 sundhedspolitik og sundhedsøkonomi       13
214                      sygdomme og sygdomsbehandling       14
215                         sygefravær og sygedagpenge       13
216                          sygehuse og akutberedskab        6
217                              syn og motorkøretøjer       10
218                                   sø- og skibsfart        9
219                               tilskud og udligning        1
220                                tinglysningsafgift         2
221                                               told        3
222                                   transportpolitik       12
223                          trossamfund og menigheder        3
224                       turisme og oplevelsesøkonomi        7
225                                  uddannelsesstøtte       14
226                               udsatte børn og unge        5
227                                     udsatte voksne        8
228                     udvalgsarbejde og -meddelelser        2
229                                 udvalgsmeddelelser        2
230                                  udviklingsbistand        1
231          udviklingssamarbejde og humanitær bistand        2
232                          udvisning og repatriering        8
233                          undersøgelseskommissioner        1
234            undervisning til unge med særlige behov        4
235                            ungdoms- og efterskoler        3
236                                      universiteter        8
237                          valg og folkeafstemninger       16
238                                  vand- og havmiljø       13
239                                      vandforsyning        5
240            vederlag mv. til medlemmer og ministre         6
241                                   vejinfrastruktur       19
242                           vejtransport og trængsel        2
243                                          veteraner        1
244                            videregående uddannelse       15
245                                    virksomhedsskat        8
246                         voksen- og efteruddannelse       21
247                                              vækst        1
248                           vækst og konkurrenceevne        2
249                          værdighed og ældrepolitik        1
250                                         værnepligt        2
251                                              ældre        6
252                             økonomi og bloktilskud        7
253                                  økonomi og finans        3

## What the 254 Sagsområder actually look like

These aren't simply 254 equally broad "political topics." They range from broad domains such as 

> finanspolitik, 
>
> socialpolitik, 
>
> transportpolitik, and 
>
>miljøpolitik og miljøbeskyttelse 

to much more specific subjects such as 

> børnetilskud,
> 
> tinglysningsafgift,
> 
> værnepligt, and 
>
> indfødsretsprøve.

There are also closely related categories. For example, employment alone includes:

> aktiv beskæftigelsesindsats
>
> arbejdsløshedsforsikring og dagpenge
>
> arbejdsmarkedspolitik og beskæftigelsesindsats
>
>arbejdsmarkedspolitik og beskæftigelsespolitik

## Can an NLP model accurately map candidate-test questions to the Folketing's official subject-area vocabulary?

Candidate-test question

        ↓

Which ODA Sagsområde(s) describe this question?

        ↓

Official Sagsområde

        ↑

Already assigned by Folketinget

        ↑

Parliamentary cases

In [29]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("intfloat/multilingual-e5-base")

c:\Users\asket\Desktop\Environments\NLP\NLP\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 4215.85it/s]

In [30]:
sagsomraader = (
    df_sagsomraade["emneord"]
    .drop_duplicates()
    .sort_values()
    .tolist()
)

len(sagsomraader)

254

In [36]:
sagsomraade_embeddings = model.encode(
    sagsomraader,
    normalize_embeddings=True,
    show_progress_bar=True
)

Batches: 100%|██████████| 8/8 [00:00<00:00, 19.14it/s]

In [37]:
question = "Integrationsydelsen skal hæves"

question_embedding = model.encode(
    [question],
    normalize_embeddings=True
)

In [38]:
import numpy as np

scores = question_embedding[0] @ sagsomraade_embeddings.T

top_indices = np.argsort(scores)[::-1][:10]

for idx in top_indices:
    print(f"{scores[idx]:.4f}  {sagsomraader[idx]}")

0.8945  indvandrere og integration
0.8719  sociale ydelser
0.8643  indfødsrets og naturalisering
0.8639  børne- og ungeydelse
0.8570  arbejdsmarkedsbidrag
0.8544  fonds- og foreningsbeskatning
0.8532  nordisk samarbejde
0.8525  kontanthjælp og uddannelseshjælp
0.8524  værdighed og ældrepolitik
0.8517  arbejdsløshedsforsikring og dagpenge

In [39]:
candidate_test_file = DATA_DIR / "candidate_test" / "Kandidattestdata.xlsx"

df_FV11 = pd.read_excel(candidate_test_file, sheet_name="FV11")
df_FV15 = pd.read_excel(candidate_test_file, sheet_name="FV15")
df_FV19 = pd.read_excel(candidate_test_file, sheet_name="FV19")
df_FV22 = pd.read_excel(candidate_test_file, sheet_name="FV22")

In [40]:
def find_sagsomraader(question, k=5):
    question_embedding = model.encode_query(
        [question],
        normalize_embeddings=True
    )

    scores = question_embedding[0] @ sagsomraade_embeddings.T
    top_indices = np.argsort(scores)[::-1][:k]

    return pd.DataFrame({
        "sagsomraade": [sagsomraader[i] for i in top_indices],
        "score": [scores[i] for i in top_indices]
    })

In [41]:
find_sagsomraader(
    "Integrationsydelsen skal hæves",
    k=5
)

                     sagsomraade     score
0     indvandrere og integration  0.894544
1                sociale ydelser  0.871928
2  indfødsrets og naturalisering  0.864276
3           børne- og ungeydelse  0.863947
4           arbejdsmarkedsbidrag  0.856957

In [47]:
df_FV19["Question"].drop_duplicates().sample(
    10,
    random_state=42
).tolist()

['Grænsekontrollen ved den dansk-tyske grænse skal gøres permanent',
 'Der skal øremærkes mere end 14 dage af barselsorloven til fædre',
 'Det skal være obligatorisk for virksomheder at have et bestemt antal kvinder i bestyrelsen',
 'Regionerne skal nedlægges',
 'Den offentlige kulturstøtte skal sænkes',
 'Danmark bruger for mange penge på forsvaret',
 'Aktiv dødshjælp for uhelbredeligt syge skal være lovligt i Danmark',
 'Der skal indføres en særlig klimaafgift på oksekød',
 'Det offentlige tilskud til privatskoler skal sænkes',
 'Man skal automatisk blive organdonor, når man fylder 18 år, medmindre man aktivt framelder sig donorregistret']

In [ ]:
test_questions = [
 'Grænsekontrollen ved den dansk-tyske grænse skal gøres permanent',
 'Der skal øremærkes mere end 14 dage af barselsorloven til fædre',
 'Det skal være obligatorisk for virksomheder at have et bestemt antal kvinder i bestyrelsen',
 'Regionerne skal nedlægges',
 'Den offentlige kulturstøtte skal sænkes',
 'Danmark bruger for mange penge på forsvaret',
 'Aktiv dødshjælp for uhelbredeligt syge skal være lovligt i Danmark',
 'Der skal indføres en særlig klimaafgift på oksekød',
 'Det offentlige tilskud til privatskoler skal sænkes',
 'Man skal automatisk blive organdonor, når man fylder 18 år, medmindre man aktivt framelder sig donorregistret']

for question in test_questions:
    print("\nQUESTION:")
    print(question)

    display(find_sagsomraader(question, k=5))

QUESTION:
Grænsekontrollen ved den dansk-tyske grænse skal gøres permanent

                            sagsomraade     score
0  fødevaresikkerhed og fødevarekontrol  0.829149
1            flygtninge og asylansøgere  0.821912
2                         skattekontrol  0.819875
3                      indfødsretsprøve  0.818973
4                       ophold og visum  0.817411

QUESTION:
Der skal øremærkes mere end 14 dage af barselsorloven til fædre

                    sagsomraade     score
0        ligestilling og barsel  0.836115
1                   færdselsret  0.822666
2              indfødsretsprøve  0.821339
3  afgift af dødsboer og gaver   0.820075
4       patent- og varemærkning  0.816665

QUESTION:
Det skal være obligatorisk for virksomheder at have et bestemt antal kvinder i bestyrelsen

                     sagsomraade     score
0         bestyrelser og ledelse  0.849445
1                virksomhedsskat  0.833623
2  køn og ligestillingsvurdering  0.830881
3           finansiel virksomhed  0.828694
4   arbejdsret og overenskomster  0.827429

QUESTION:
Regionerne skal nedlægges

                    sagsomraade     score
0           byråd og regionsråd  0.855688
1                      regioner  0.854880
2                landdistrikter  0.850424
3  kommunal og regional økonomi  0.849182
4            udvalgsmeddelelser  0.844960

QUESTION:
Den offentlige kulturstøtte skal sænkes

                                    sagsomraade     score
0                        kultur- og kunststøtte  0.906912
1                             uddannelsesstøtte  0.858718
2                 kulturformidling og kulturliv  0.852075
3  partistøtte, partiregnskaber og gruppestøtte  0.849131
4                          arbejdsmarkedsbidrag  0.848164

QUESTION:
Danmark bruger for mange penge på forsvaret

                                  sagsomraade     score
0                                   forsvaret  0.877893
1                           militært materiel  0.839036
2                             politi og våben  0.838245
3                      økonomi og bloktilskud  0.837838
4  efterretningstjeneste og sikkerhedspolitik  0.836239

QUESTION:
Aktiv dødshjælp for uhelbredeligt syge skal være lovligt i Danmark

                              sagsomraade     score
0                     hjælp til pårørende  0.846955
1            afgift af dødsboer og gaver   0.844186
2             aktiv beskæftigelsesindsats  0.839531
3               sygehuse og akutberedskab  0.838965
4  patientrettigheder og patientsikkerhed  0.838643

QUESTION:
Der skal indføres en særlig klimaafgift på oksekød

                         sagsomraade     score
0                      miljøafgifter  0.879415
1                    energiafgifter   0.865781
2                      punktafgifter  0.859052
3       afgift af dødsboer og gaver   0.849087
4  klimapolitik og klimaforandringer  0.845595

QUESTION:
Det offentlige tilskud til privatskoler skal sænkes

               sagsomraade     score
0  ungdoms- og efterskoler  0.848842
1        uddannelsesstøtte  0.845968
2   økonomi og bloktilskud  0.843308
3     tilskud og udligning  0.838223
4              folkeskolen  0.837744

QUESTION:
Man skal automatisk blive organdonor, når man fylder 18 år, medmindre man aktivt framelder sig donorregistret

                    sagsomraade     score
0           hjælp til pårørende  0.830119
1  afgift af dødsboer og gaver   0.824840
2              indfødsretsprøve  0.823602
3                 miljøafgifter  0.822755
4       videregående uddannelse  0.821774

:

It is clear that some questions are easier to find topics, especially topics that are actually voted on in parliament. Questions that are about a very narrow or specific topic such as 

> Aktiv dødshjælp for uhelbredeligt syge skal være lovligt i Danmark
>
> or 
>
> Regionerne skal nedlægges

are more difficult to find topics for. The question becomes wether we handle this again as a more broad topic discussion. So we decide that "*Aktiv dødshjælp for uhelbredeligt syge skal være lovligt i Danmark*" is not about that a vote in parliament about that, because that never happened, but more about *patientrettigheder og patientsikkerhed*.